### ISSUE TITLE
Mojave support?

### ISSUE THREAD

**Issue by mjabdulm** [dwarvesf/blurred#5]
Hi,

Is it possible to support Mojave?

**Comment by phucledien** [comment]
Hi @mjabdulm 😄 

This product is a place for us to experiment with SwiftUI (a new UI framework), and sadly it just supports macOS Catalina.

So if anyone still using a lower macOS version but interested in this project, you guys can fork this repo and make another version that supports lower macOS.

**Comment by mjabdulm** [comment]
Thanks for the prompt response. I'll see if I can find some interested soul.
