### ISSUE TITLE
What is "Single" vs "Parallel" mode?

### ISSUE THREAD

**Issue by dsernst** [dwarvesf/blurred#6]
Can you explain the difference between `Blur Mode:` "Single" vs "Parallel"?

Unclear what this Preferences option does.
Not seeing any noticeable difference.

**Comment by phucledien** [comment]
Hi @dsernst, thank you for using our app 👍 

So the Single or Parallel mode just affects when you are using multiple displays.

In single mode, just your main screen will have the blur effect
In parallel mode, all your screen will have the blur effect

If you have other concern, feel free to ask us here 👍

**Comment by dsernst** [comment]
Ah, got it. Thanks 🙌
